import localFont from "next/font/local";
import { Providers } from "./providers";
import { ToastContainer } from 'react-toastify'
import "./globals.css";
import Nav from "../components/nav/Nav";
import ButonPdf from '../components/componentsPage/ButonPdf'
import ButtonWts from '../components/componentsPage/ButtonWts'
import 'react-toastify/dist/ReactToastify.css'

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Machine learning",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {
          <Providers>
            <ToastContainer />
            <Nav />
            {children}
            <ButonPdf/>
            <ButtonWts/>
          </Providers>
        }
      </body>
    </html>
  );
}
